<style>  
.hideme{display:none;}
</style>

<a href="#" class="noob">
    wololo wololo
</a>

<?php 

var_dump($this->getData('countries'))

;?>

<script type="text/x-magento-init">
    {
        "*": {
            "Dlaweb_Map/js/dropdown":{
                "AjaxUrl":"<?php echo $block->getAjaxUrl();?>"
            }
        }
    }
</script>

<div id='test' class="hideme">
    dropdown
    <select>
    <% _.each(posts, function(text,value) { %>
        <option value="<%= value %>"><%= text %></option>
    <% }) %> 
    </select>
</div>